version: "3.9"
services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
      - "25575:25575"
    volumes:
      - ./minecraft-data:/data
    environment:
      MEMORY: 6G
    deploy:
      resources:
        limits:
          memory: 7000m
    restart: always